// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	address: "http://localhost:8200"
	auth: {
		method: "kubernetes"
		mount:  "kubernetes"
	}
	secret: {
		destination: {
			name: "example-secret"
		}
		path: "app/secret"
		type: "kv-v2"
		mount: "kv"
	}
	serviceAccount: {
		create: true
	}
}
