// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Placeholder for user-supplied values.
values: {
	vault: {
		server: {
			address: "http://host.docker.internal:8200"
			auth: {
				kubernetes: {
					role: "oauth-vault"
				}
			}
			identity: {
				jwt: {
					issuer:   ""
					audience: ""
				}
			}
		}
	}
}
